### ISSUE TITLE
Querying multiple identifiers at the same time for genomic signature  BUG

### ISSUE THREAD

**Issue by Tardins** [openbiox/UCSCXenaShiny#235] opened 2021-12-15 16:51 UTC
December 15th, 2021

Greetings!

When querying with signatures (formulas containing gene names), I have had some problems because I'm querying with multiple genes (number of genes in signatures = 133) and i see this warning "Querying multiple identifiers at the same time for genomic signature" in rstudio. When querying signatures, using only few genes I don't have this problem. I would like to know if there is a limitation on the number of genes I can include in a formula, or or this could just be a bug

Regards,

Alan T.

**Comment by ShixiangWang** [comment] 2021-12-31 02:18
I did not notice the message. Sorry for the late reply.

I think the problem is due to failed match in your input. There shouldn't have any limitation of the gene number. Would you mind posting your command so I check in more depth?

**Comment by ShixiangWang** [comment] 2022-01-08 16:35
@Tardins This issue may be related to https://github.com/openbiox/UCSCXenaShiny/issues/234#issuecomment-992069647. Could you try and see how it works?

**Comment by ShixiangWang** [comment] 2022-01-27 06:45
I am closing it now. Free to reopen if this still exists.

**Closed by ShixiangWang** 2022-01-27 06:45 UTC
