### ISSUE TITLE
Error: Quick PanCan Analysis, TCGA: Association between Molecular Profile And TMB/Stemness/MSI (radar show)

### ISSUE THREAD

**Issue by quiquemedina** [openbiox/UCSCXenaShiny#254] opened 2023-04-18 17:44 UTC
While running UCSCXenaShiny v1.1.10 based on UCSCXenaTools v1.4.8 from RStudio, we get the following error message:
Error: unused arguments (font.radar = "sans", values.radar = c("-1", "0", "1"), grid.min = -1, grid.mid = 0, grid.max = 1, background.circle.colour = "white", gridline.mid.colour = "grey", group.line.width = 1, group.point.size = 3, group.colours = "#00AFBB", plot.title = paste0(input$Pancan_search, " ", input$profile, " ", input$Type, " "))

Could you please advise on how to correct the error message.
Thank you.
Enrique Medina-Acosta
[Error Radar Stemnes in UCSCXenaShiny v1.1.10.pdf](https://github.com/openbiox/UCSCXenaShiny/files/11264732/Error.Radar.Stemnes.in.UCSCXenaShiny.v1.1.10.pdf)

**Comment by ShixiangWang** [comment] 2023-04-19 04:18
@quiquemedina Hi, it works normally on hiplot, https://hiplot.cn/advance/ucsc-xena-shiny

![image](https://user-images.githubusercontent.com/25057508/232965706-42ec1993-ae2d-43f8-95ce-2637bfa8b788.png)

Based on your info, I guess the ggradar package (used for this plot) may change its function signature (i.e. options) after some specified version. I will check how to make it work again.

**Comment by ShixiangWang** [comment] 2023-04-19 04:24
It is strange that all options could be found in the latest code of ggradar. https://github.com/ricardo-bion/ggradar/blob/eefe750b726afad4c3f69b1b461d8f427b96f68c/R/ggradar.R

I will test it locally further.

**Comment by ShixiangWang** [comment] 2023-04-19 04:36
Unfortunately, in local Windows I cannot reproduce this. Could you restart R session, reinstall ggradar, UCSCXenaShiny from CRAN and try again?

![image](https://user-images.githubusercontent.com/25057508/232967741-ca856e1a-60bd-4f7b-9356-9d6e5ce7dd0b.png)


```
> devtools::session_info()
─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.0 (2022-04-22 ucrt)
 os       Windows 10 x64 (build 22621)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  Chinese (Simplified)_China.utf8
 ctype    Chinese (Simplified)_China.utf8
 tz       Asia/Taipei
 date     2023-04-19
 rstudio  2022.07.2+576 Spotted Wakerobin (desktop)
 pandoc   NA

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package          * version    date (UTC) lib source
 abind              1.4-5      2016-07-21 [1] CRAN (R 4.1.0)
 assertthat         0.2.1      2019-03-21 [1] CRAN (R 4.1.0)
 backports          1.4.1      2021-12-13 [1] CRAN (R 4.1.2)
 bayestestR         0.12.1     2022-05-02 [1] CRAN (R 4.2.0)
 brio               1.1.3      2021-11-30 [1] CRAN (R 4.1.2)
 broom              0.8.0      2022-04-13 [1] CRAN (R 4.2.0)
 bslib              0.3.1      2021-10-06 [1] CRAN (R 4.1.2)
 cachem             1.0.6      2021-08-19 [1] CRAN (R 4.1.2)
 Cairo              1.6-0      2022-07-05 [1] CRAN (R 4.2.2)
 callr              3.7.0      2021-04-20 [1] CRAN (R 4.1.0)
 car                3.0-13     2022-05-02 [1] CRAN (R 4.2.0)
 carData            3.0-5      2022-01-06 [1] CRAN (R 4.1.2)
 cli                3.4.1      2022-09-23 [1] CRAN (R 4.2.1)
 coda               0.19-4     2020-09-30 [1] CRAN (R 4.1.0)
 colorspace         2.0-3      2022-02-21 [1] CRAN (R 4.1.2)
 colourpicker     * 1.1.1      2021-10-04 [1] CRAN (R 4.1.2)
 correlation        0.8.1      2022-05-20 [1] CRAN (R 4.2.0)
 cowplot          * 1.1.1      2020-12-30 [1] CRAN (R 4.1.0)
 crayon             1.5.1      2022-03-26 [1] CRAN (R 4.1.3)
 crosstalk          1.2.0      2021-11-04 [1] CRAN (R 4.1.2)
 curl               4.3.2      2021-06-23 [1] CRAN (R 4.1.0)
 data.table       * 1.14.2     2021-09-27 [1] CRAN (R 4.1.2)
 datawizard         0.4.1      2022-05-16 [1] CRAN (R 4.2.0)
 DBI                1.1.2      2021-12-20 [1] CRAN (R 4.1.2)
 desc               1.4.1      2022-03-06 [1] CRAN (R 4.1.2)
 devtools           2.4.3      2021-11-30 [1] CRAN (R 4.1.3)
 digest             0.6.29     2021-12-01 [1] CRAN (R 4.1.2)
 dplyr            * 1.0.9      2022-04-28 [1] CRAN (R 4.2.0)
 DT               * 0.23       2022-05-10 [1] CRAN (R 4.2.0)
 ellipsis           0.3.2      2021-04-29 [1] CRAN (R 4.1.0)
 emmeans            1.7.4-1    2022-05-15 [1] CRAN (R 4.2.0)
 estimability       1.3        2018-02-11 [1] CRAN (R 4.2.0)
 ezcox            * 1.0.2      2021-10-28 [1] CRAN (R 4.1.2)
 fansi              1.0.3      2022-03-24 [1] CRAN (R 4.2.0)
 farver             2.1.0      2021-02-28 [1] CRAN (R 4.1.0)
 fastmap            1.1.0      2021-01-25 [1] CRAN (R 4.1.0)
 fontawesome        0.2.2      2021-07-02 [1] CRAN (R 4.1.2)
 forcats            0.5.1      2021-01-27 [1] CRAN (R 4.1.0)
 forestmodel        0.6.3      2022-02-16 [1] local
 fs               * 1.5.2      2021-12-08 [1] CRAN (R 4.1.2)
 generics           0.1.2      2022-01-31 [1] CRAN (R 4.1.2)
 gganatogram      * 1.1.1      2021-07-15 [1] Github (jespermaag/gganatogram@1ecc42e)
 ggcorrplot       * 0.1.3      2019-05-19 [1] CRAN (R 4.1.0)
 ggplot2          * 3.3.6.9000 2022-10-10 [1] Github (tidyverse/ggplot2@e93e053)
 ggpolypath       * 0.1.0      2016-08-10 [1] CRAN (R 4.1.0)
 ggpubr           * 0.4.0      2020-06-27 [1] CRAN (R 4.1.0)
 ggradar          * 0.2        2021-07-15 [1] Github (ricardo-bion/ggradar@63e5cef)
 ggsignif           0.6.3      2021-09-09 [1] CRAN (R 4.1.2)
 ggstatsplot      * 0.9.2      2022-05-21 [1] CRAN (R 4.2.0)
 glue               1.6.2      2022-02-24 [1] CRAN (R 4.1.2)
 gridExtra          2.3        2017-09-09 [1] CRAN (R 4.1.0)
 gtable             0.3.0      2019-03-25 [1] CRAN (R 4.1.0)
 hms                1.1.1      2021-09-26 [1] CRAN (R 4.1.2)
 htmltools          0.5.2      2021-08-25 [1] CRAN (R 4.1.2)
 htmlwidgets        1.5.4      2021-09-08 [1] CRAN (R 4.1.2)
 httpuv             1.6.5      2022-01-05 [1] CRAN (R 4.1.2)
 httr               1.4.3      2022-05-04 [1] CRAN (R 4.2.0)
 insight            0.17.1     2022-05-13 [1] CRAN (R 4.2.0)
 jquerylib          0.1.4      2021-04-26 [1] CRAN (R 4.1.0)
 jsonlite           1.8.0      2022-02-22 [1] CRAN (R 4.1.2)
 km.ci              0.5-6      2022-04-06 [1] CRAN (R 4.1.3)
 KMsurv             0.1-5      2012-12-03 [1] CRAN (R 4.1.0)
 knitr              1.39       2022-04-26 [1] CRAN (R 4.2.0)
 labeling           0.4.2      2020-10-20 [1] CRAN (R 4.1.0)
 later              1.3.0      2021-08-18 [1] CRAN (R 4.1.2)
 lattice            0.20-45    2021-09-22 [1] CRAN (R 4.1.2)
 lazyeval           0.2.2      2019-03-15 [1] CRAN (R 4.1.0)
 lifecycle          1.0.3      2022-10-07 [1] CRAN (R 4.2.1)
 magrittr         * 2.0.3      2022-03-30 [1] CRAN (R 4.2.0)
 markdown           1.1        2019-08-07 [1] CRAN (R 4.1.0)
 MASS               7.3-57     2022-04-22 [1] CRAN (R 4.2.0)
 Matrix             1.5-1      2022-09-13 [1] CRAN (R 4.2.2)
 memoise            2.0.1      2021-11-26 [1] CRAN (R 4.1.2)
 mime               0.12       2021-09-28 [1] CRAN (R 4.1.1)
 miniUI             0.1.1.1    2018-05-18 [1] CRAN (R 4.1.0)
 mnormt             2.0.2      2020-09-01 [1] CRAN (R 4.1.0)
 munsell            0.5.0      2018-06-12 [1] CRAN (R 4.1.0)
 mvtnorm            1.1-3      2021-10-08 [1] CRAN (R 4.1.1)
 nlme               3.1-157    2022-03-25 [1] CRAN (R 4.1.3)
 pacman           * 0.5.1      2019-03-11 [1] CRAN (R 4.1.0)
 paletteer          1.4.0      2021-07-20 [1] CRAN (R 4.1.0)
 parameters         0.17.0     2022-03-10 [1] CRAN (R 4.1.3)
 patchwork          1.1.1      2020-12-17 [1] CRAN (R 4.1.0)
 performance        0.9.0      2022-03-30 [1] CRAN (R 4.1.3)
 pillar             1.7.0      2022-02-01 [1] CRAN (R 4.1.2)
 pkgbuild           1.3.1      2021-12-20 [1] CRAN (R 4.1.2)
 pkgconfig          2.0.3      2019-09-22 [1] CRAN (R 4.1.0)
 pkgload            1.2.4      2021-11-30 [1] CRAN (R 4.1.2)
 plotly           * 4.10.0     2021-10-09 [1] CRAN (R 4.1.2)
 ppcor              1.1        2015-12-03 [1] CRAN (R 4.1.0)
 prettyunits        1.1.1      2020-01-24 [1] CRAN (R 4.1.0)
 processx           3.5.3      2022-03-25 [1] CRAN (R 4.2.0)
 promises           1.2.0.1    2021-02-11 [1] CRAN (R 4.1.0)
 ps                 1.7.0      2022-04-23 [1] CRAN (R 4.2.0)
 psych              2.2.5      2022-05-10 [1] CRAN (R 4.2.0)
 purrr            * 0.3.4      2020-04-17 [1] CRAN (R 4.1.0)
 R.methodsS3      * 1.8.1      2020-08-26 [1] CRAN (R 4.1.0)
 R.oo             * 1.24.0     2020-08-26 [1] CRAN (R 4.1.0)
 R.utils          * 2.11.0     2021-09-26 [1] CRAN (R 4.1.2)
 R6                 2.5.1      2021-08-19 [1] CRAN (R 4.1.2)
 RColorBrewer     * 1.1-3      2022-04-03 [1] CRAN (R 4.1.3)
 Rcpp               1.0.8.3    2022-03-17 [1] CRAN (R 4.1.3)
 readr              2.1.2      2022-01-30 [1] CRAN (R 4.1.2)
 rematch2           2.1.2      2020-05-01 [1] CRAN (R 4.1.0)
 remotes            2.4.2      2021-11-30 [1] CRAN (R 4.1.2)
 rlang              1.0.6      2022-09-24 [1] CRAN (R 4.2.1)
 rprojroot          2.0.3      2022-04-02 [1] CRAN (R 4.1.3)
 rsconnect          0.8.25     2021-11-19 [1] CRAN (R 4.1.2)
 rstatix            0.7.0      2021-02-13 [1] CRAN (R 4.1.0)
 rstudioapi         0.13       2020-11-12 [1] CRAN (R 4.1.0)
 sass               0.4.1      2022-03-23 [1] CRAN (R 4.1.3)
 scales             1.2.0      2022-04-13 [1] CRAN (R 4.2.0)
 sessioninfo        1.2.2      2021-12-06 [1] CRAN (R 4.1.2)
 shiny            * 1.7.1      2021-10-02 [1] CRAN (R 4.1.2)
 shinyalert       * 3.0.0      2021-12-20 [1] CRAN (R 4.1.2)
 shinyBS          * 0.61.1     2022-04-17 [1] CRAN (R 4.2.0)
 shinyFiles       * 0.9.1      2021-11-10 [1] CRAN (R 4.1.2)
 shinyjs          * 2.1.0      2021-12-23 [1] CRAN (R 4.1.2)
 shinythemes      * 1.2.0      2021-01-25 [1] CRAN (R 4.1.0)
 shinyWidgets     * 0.7.0      2022-05-11 [1] CRAN (R 4.2.0)
 statsExpressions   1.3.2      2022-05-20 [1] CRAN (R 4.2.0)
 stringi            1.7.6      2021-11-29 [1] CRAN (R 4.1.2)
 stringr          * 1.4.0      2019-02-10 [1] CRAN (R 4.1.0)
 survival         * 3.3-1      2022-03-03 [1] CRAN (R 4.1.2)
 survminer        * 0.4.9      2021-03-09 [1] CRAN (R 4.1.0)
 survMisc           0.5.6      2022-04-07 [1] CRAN (R 4.1.3)
 testthat           3.1.4      2022-04-26 [1] CRAN (R 4.2.0)
 tibble             3.1.7      2022-05-03 [1] CRAN (R 4.2.0)
 tidyr            * 1.2.0      2022-02-01 [1] CRAN (R 4.1.2)
 tidyselect         1.1.2      2022-02-21 [1] CRAN (R 4.1.2)
 tmvnsim            1.0-2      2016-12-15 [1] CRAN (R 4.1.0)
 tzdb               0.3.0      2022-03-28 [1] CRAN (R 4.1.3)
 UCSCXenaShiny    * 1.1.10     2023-02-28 [1] CRAN (R 4.2.3)
 UCSCXenaTools    * 1.4.8      2022-06-20 [1] CRAN (R 4.2.3)
 usethis            2.1.5      2021-12-09 [1] CRAN (R 4.1.2)
 utf8               1.2.2      2021-07-24 [1] CRAN (R 4.1.2)
 vctrs              0.4.1      2022-04-13 [1] CRAN (R 4.2.0)
 viridisLite        0.4.0      2021-04-13 [1] CRAN (R 4.1.0)
 waiter           * 0.2.5      2022-01-03 [1] CRAN (R 4.1.2)
 withr              2.5.0      2022-03-03 [1] CRAN (R 4.1.2)
 xfun               0.31       2022-05-10 [1] CRAN (R 4.2.0)
 xtable             1.8-4      2019-04-21 [1] CRAN (R 4.1.0)
 yaml               2.3.5      2022-02-21 [1] CRAN (R 4.1.2)
 zeallot            0.1.0      2018-01-28 [1] CRAN (R 4.1.0)
 zip              * 2.2.0      2021-05-31 [1] CRAN (R 4.1.0)
 zoo                1.8-10     2022-04-15 [1] CRAN (R 4.2.0)

 [1] D:/Rlib
 [2] C:/Users/Administrator/AppData/Local/R/win-library/4.2
 [3] C:/Program Files/R/R-4.2.0/library
```

**Comment by quiquemedina** [comment] 2023-04-19 15:06
Dear Shixiang Wang, 

The problem is with the UCSCXenaShiny version 1.1.10 in Windows RStudio. 
The hiplot, https://hiplot.cn/advance/ucsc-xena-shiny, is version 1.1.9, and it does work ok, but the error I get is with v1.1.10.
As you suggested, I uninstalled R.4.2.3, UCSCXena vs 1.1.10, ggradar. 
I Reinstalled R.4.2.3, UCSCXena vs 1.1.10 from CRAN, and “ricardo-bion/ggradar" from github with dependencies. 

The ggradar in RStudio is working and plotting, tested with the code:
mtcars_radar <- mtcars %>% 
  as_tibble(rownames = "group") %>% 
  mutate_at(vars(-group), rescale) %>% 
  tail(4) %>% 
  select(1:10)
ggradar(mtcars_radar)


 

But, it does not plot using the UCSCXenaShiny v.1.1.10, Example code:

## To generate a radar plot, uncomment the following code
p = vis_gene_stemness_cor(
 Gene = "`MT-ATP8` + `MT-ATP6` + `MT-CO1` + `MT-CO2` + `MT-CO3` + `MT-CYB` + `MT-ND1` + `MT-ND2` + `MT-ND3` + `MT-ND4L` + `MT-ND4` + `MT-ND5` + `MT-ND6`", 
 cor_method = "spearman",
 data_type = "mRNA",
 Plot = "TRUE"
)
pdata <- p$data %>%
 dplyr::mutate(cor = round(cor, digits = 3), p.value = round(p.value, digits = 3))
df <- pdata %>%
 select(cor, cancer) %>%
 pivot_wider(names_from = cancer, values_from = cor)
df$gene <- "Gene signature"
df<-df[,c(34,1:33)]
ggradar::ggradar(
 df[1, ],
 font.radar = "sans",
 values.radar = c("-1", "0", "1"),
 grid.min = -1, grid.mid = 0, grid.max = 1,
 # Background and grid lines
 background.circle.colour = "white",
 gridline.mid.colour = "grey",
 # Polygons
 group.line.width = 1,
 group.point.size = 3,
 group.colours = "# 00AFBB",
) + theme(plot.title = element_text(hjust = .5)) 

It generates the error message and it does no plot:

Error in ggradar::ggradar(df[1, ], font.radar = "sans", values.radar = c("-1",  : 
  unused arguments (font.radar = "sans", values.radar = c("-1", "0", "1"), grid.min = -1, grid.mid = 0, grid.max = 1, background.circle.colour = "white", gridline.mid.colour = "grey", group.line.width = 1, group.point.size = 3, group.colours = "# 00AFBB")



The same error message remains in the app_run()

 

devtools::install_github("ricardo-bion/ggradar", 
                          dependencies = TRUE, force = TRUE)

Could you please advise on how to correct the error message.
Thank you.
Enrique Medina-Acosta
[Error Radar Stemnes in UCSCXenaShiny v1.1.10)_cont.pdf](https://github.com/openbiox/UCSCXenaShiny/files/11274582/Error.Radar.Stemnes.in.UCSCXenaShiny.v1.1.10._cont.pdf)

**Comment by quiquemedina** [comment] 2023-04-19 18:59
The error message indicates that there are unused arguments in the ggradar() function call. Specifically, the arguments font.radar, values.radar, grid.min, grid.mid, grid.max, background.circle.colour, gridline.mid.colour, group.line.width, group.point.size, and group.colours are not recognized by the function.

In RStudio, I can fix the error by removing the unused arguments from the ggradar() function call running:
ggradar::ggradar(
  df[1, ],
  # remove unused arguments
) +
theme(plot.title = element_text(hjust = .5))

And the radar os plotted. 

Thus, I undersatnd thta ggradar unused arguments must be revised in the UCSCXEnaShiny v1.1.1
[Rplot ggradar fixed 1.pdf](https://github.com/openbiox/UCSCXenaShiny/files/11276659/Rplot.ggradar.fixed.1.pdf)
0

**Comment by ShixiangWang** [comment] 2023-04-20 06:22
@quiquemedina Thanks for your further response. I dived in and found this problem is due to the strange and significant change of ggradar (https://github.com/ricardo-bion/ggradar/issues/57#issuecomment-1515774117). Use a previous version will pass the issue. In current stage, it is not proper to modify the UCSCXenaShiny code to fit the recent change from ggradar as it break backward compatibility.

```r
devtools::install_github("ricardo-bion/ggradar@345535f")

library(UCSCXenaShiny)
library(tidyverse)

p = vis_gene_stemness_cor(
  Gene = "`MT-ATP8` + `MT-ATP6` + `MT-CO1` + `MT-CO2` + `MT-CO3` + `MT-CYB` + `MT-ND1` + `MT-ND2` + `MT-ND3` + `MT-ND4L` + `MT-ND4` + `MT-ND5` + `MT-ND6`", 
  cor_method = "spearman",
  data_type = "mRNA",
  Plot = "TRUE"
)
pdata <- p$data %>%
  dplyr::mutate(cor = round(cor, digits = 3), p.value = round(p.value, digits = 3))
df <- pdata %>%
  select(cor, cancer) %>%
  pivot_wider(names_from = cancer, values_from = cor)
df$gene <- "Gene signature"
df<-df[,c(34,1:33)]
df

ggradar::ggradar(
  df[1, ],
  font.radar = "sans",
  values.radar = c("-1", "0", "1"),
  grid.min = -1, grid.mid = 0, grid.max = 1,
  # Background and grid lines
  background.circle.colour = "white",
  gridline.mid.colour = "grey",
  # Polygons
  group.line.width = 1,
  group.point.size = 3,
  group.colours = "#00AFBB",
) + theme(plot.title = element_text(hjust = .5)) 

devtools::session_info()

```

**Comment by quiquemedina** [comment] 2023-04-20 15:30
Your suggestion resolved the issues. 

Many, many thanks.

Enrique

**Comment by ShixiangWang** [comment] 2023-04-21 09:21
@quiquemedina :). I am closing this now as https://github.com/ricardo-bion/ggradar/issues/57 is completed.

**Closed by ShixiangWang** 2023-04-21 09:21 UTC
